name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Build assets for release
        run: npm run build

      - name: Commit build artifacts to release branch
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/build/ -f
          git commit -m "chore: include compiled assets for release ${{ github.ref_name }}" || echo "No changes"
          git push origin HEAD:refs/heads/release/${{ github.ref_name }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            public/build/**
